version: "2"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 3000:3000/tcp
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - /home/benjamin/portainer/adguardhome/workdir:/opt/adguardhome/work
      - /home/benjamin/portainer/adguardhome/confdir:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      hostNetwork:
        ipv4_address: 192.168.100.10

networks:
  hostNetwork:
    external: true
