version: "3"
services:
    db:
        image: postgres:11-alpine
        environment:
            POSTGRES_DB: wiki
            POSTGRES_PASSWORD: <>
            POSTGRES_USER: <>
        logging:
            driver: "none"
        restart: unless-stopped
        volumes:
            - /home/benjamin/portainer/wikijs/db-data:/var/lib/postgresql/data
        networks:
            hostNetwork:
                ipv4_address: 192.168.<>.<>

    wiki:
        image: requarks/wiki:2
        depends_on:
            - db
        environment:
            DB_TYPE: postgres
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: <>
            DB_PASS: <>
            DB_NAME: wiki
        restart: unless-stopped
        networks:
            hostNetwork:
                ipv4_address: 192.168.<>.<>
        # Cant manually set the port to 80 because the container attaches itself
        # directly to the IP instead of a host.
        # ports:
        #     - "80:3000"

networks:
    hostNetwork:
        external: true
