---
header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "#fff5f2"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "Hardware"
    icon: "fas fa-server"
    items:
      - name: "Router"
        logo: "https://www.bahama.site/storage/icons/opnsense.png"
        subtitle: "OPNSense"
        url: "http://192.168.100.1/"
        target: "_blank" 
      - name: "Switch"
        logo: "https://i.pinimg.com/originals/45/a7/63/45a7633eb514acbc2a7d54c423962a9b.png"
        subtitle: "Ubiquiti"
        url: "https://192.168.100.16/"
        target: "_blank" 
      - name: "Access Point"
        logo: "https://image.winudf.com/v2/image/Y29tLmNpc2NvLmNvbm5lY3QuY2xvdWRfaWNvbl8xNTExMjU0NzA5XzA0MQ/icon.png?w=170&fakeurl=1&type=.png"
        subtitle: "Linksys"
        url: "http://192.168.100.11/wireless/wireless_basic.shtml"
        target: "_blank" 



  - name: "Servers"
    icon: "fas fa-cloud"
    items:
      - name: "Proxmox"
        logo: "https://www.excellent.co.id/wp-content/uploads/2014/07/Proxmox_symbol-768x768.png"
        subtitle: "Proxmox Virtual Environment"
        tag: "app"
        url: "https://192.168.100.185:8006/"
        target: "_blank" 
      - name: "Portainer"
        logo: "https://autoize.com/wp-content/uploads/2017/02/Portainer-logo-300x300.png"
        subtitle: "Portainer.io"
        url: "http://192.168.100.197/#!/2/docker/dashboard"
        target: "_blank" 
      - name: "OMV local"
        logo: "https://alternative.me/media/256/openmediavault-icon-iodqeg0cabtm6mpc-c.png"
        subtitle: "OpenMediaVault"
        url: "https://192.168.100.195/#/dashboard"
        target: "_blank" 
      - name: "OMV public"
        logo: "https://alternative.me/media/256/openmediavault-icon-iodqeg0cabtm6mpc-c.png"
        subtitle: "OpenMediaVault"
        url: "https://192.168.100.193/#/dashboard"
        target: "_blank" 

  - name: "Apps"
    icon: "fas fa-apple-alt"
    items:
      - name: "Wiki"
        logo: "https://cdn-images.threadless.com/threadless-media/artist_shops/shops/wikijs/products/669711/shirt-1531875065-b80b73dd568a551445296d8a5cdcf3ca.png?v=3&d=eyJvbmx5X21ldGEiOiBmYWxzZSwgImZvcmNlIjogZmFsc2UsICJvcHMiOiBbWyJ0cmltIiwgW2ZhbHNlLCBmYWxzZV0sIHt9XSwgWyJyZXNpemUiLCBbXSwgeyJ3aWR0aCI6IDk5Ni4wLCAiYWxsb3dfdXAiOiBmYWxzZSwgImhlaWdodCI6IDk5Ni4wfV0sIFsiY2FudmFzX2NlbnRlcmVkIiwgWzEyMDAsIDEyMDBdLCB7ImJhY2tncm91bmQiOiAiMDAwMDAwIn1dLCBbInJlc2l6ZSIsIFs4MDBdLCB7fV0sIFsiY2FudmFzX2NlbnRlcmVkIiwgWzgwMCwgODAwLCAiI2ZmZmZmZiJdLCB7fV0sIFsiZW5jb2RlIiwgWyJqcGciLCA4NV0sIHt9XV19"
        subtitle: "Wiki.js"
        url: "http://192.168.100.51:3000/"
        target: "_blank" 
