---
header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "#fff5f2"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "Servers"
    icon: "fas fa-cloud"
    items:
      - name: "Proxmox"
        logo: "https://www.excellent.co.id/wp-content/uploads/2014/07/Proxmox_symbol-768x768.png"
        subtitle: "Proxmox Virtual Environment"
        tag: "app"
        url: "https://192.168.100.185:8006/"
        target: "_blank" 
      - name: "Portainer"
        logo: "https://autoize.com/wp-content/uploads/2017/02/Portainer-logo-300x300.png"
        subtitle: "Portainer.io"
        url: "http://192.168.100.197/#!/2/docker/dashboard"
        target: "_blank" 
      - name: "OMV local"
        logo: "https://alternative.me/media/256/openmediavault-icon-iodqeg0cabtm6mpc-c.png"
        subtitle: "OpenMediaVault"
        url: "http://192.168.100.195/#/"
        target: "_blank" 
      - name: "OMV public"
        logo: "https://alternative.me/media/256/openmediavault-icon-iodqeg0cabtm6mpc-c.png"
        subtitle: "OpenMediaVault"
        url: "http://192.168.100.193/#/"
        target: "_blank" 
