---
header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "#fff5f2"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "Apps"
    icon: "fas fa-apple-alt"
    items:
      - name: "Wiki"
        logo: "../assets/icons/wikijs.png"
        subtitle: "Wiki.js"
        url: "http://192.168.100.51:3000/"
      - name: "Plex"
        logo: "../assets/icons/plex.png"
        subtitle: "Movies, TV Shows"
        url: "http://192.168.100.203:32400/web/index.html#!/"
      - name: "AdGuard Home"
        logo: "../assets/icons/AdGuardHome.webp"
        subtitle: "DNS Ad blocker, local DNS"
        url: "http://192.168.100.1:81"

  - name: "Servers"
    icon: "fas fa-cloud"
    items:
      - name: "Proxmox"
        logo: "../assets/icons/proxmox.png"
        subtitle: "Proxmox Virtual Environment"
        tag: "app"
        url: "https://192.168.100.185:8006/"
      - name: "Portainer"
        logo: "../assets/icons/portainer.png"
        subtitle: "Portainer.io"
        url: "http://192.168.100.208/#!/2/docker/dashboard"
      - name: "OMV local"
        logo: "../assets/icons/omv.png"
        subtitle: "OpenMediaVault"
        url: "https://192.168.100.202/#/dashboard"
      - name: "OMV public"
        logo: "../assets/icons/omv.png"
        subtitle: "OpenMediaVault"
        url: "https://192.168.100.205/#/dashboard"

  - name: "Hardware"
    icon: "fas fa-server"
    items:
      - name: "Router"
        logo: "../assets/icons/opnsense.png"
        subtitle: "OPNSense"
        url: "http://192.168.100.1/"
      - name: "Switch"
        logo: "../assets/icons/ubiquiti.png"
        subtitle: "Ubiquiti"
        url: "https://192.168.207.16/"
      - name: "Access Point"
        logo: "../assets/icons/linksys.webp"
        subtitle: "Linksys"
        url: "http://192.168.200.11/wireless/wireless_basic.shtml"
