---
header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "#fff5f2"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "#181C3A"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "Entertainment"
    icon: "fas fa-theater-masks"
    items:
      - name: "Netflix"
        logo: "../assets/icons/netflix.png"
        subtitle: "Netflix"
        url: "https://www.netflix.com/browse"
      - name: "Disney Plus"
        logo: "../assets/icons/disneyplus.png"
        subtitle: "Disney Plus"
        url: "https://www.disneyplus.com/home"
      - name: "HBO Max"
        logo: "../assets/icons/hbo-max.png"
        subtitle: "HBO Max"
        url: "https://play.hbomax.com/page/urn:hbo:page:home?reentered=true&userProfileType=liteUserProfile"
      - name: "Prime Video"
        logo: "../assets/icons/prime-video.png"
        subtitle: "Amazon Prime Video"
        url: "https://www.amazon.com/Amazon-Video/b?node=2858778011"
  
  - name: "Dev Ops"
    icon: "fas fa-cloud"
    items:
      - name: "AWS"
        logo: "../assets/icons/aws.png"
        subtitle: "Amazon Web Services"
        url: "https://console.aws.amazon.com/console/home?region=us-east-1"
      - name: "ZeroTier"
        logo: "../assets/icons/zerotier.png"
        subtitle: "ZeroTier Central"
        url: "https://my.zerotier.com/network/b6079f73c64a1109"
      - name: "GCP"
        logo: "../assets/icons/gcp.webp"
        subtitle: "Google Cloud Platform"
        url: "https://console.cloud.google.com/getting-started"
      - name: "CloudFlare"
        logo: "../assets/icons/cloudflare.webp"
        subtitle: "Cloudflare"
        url: "https://dash.cloudflare.com/083031929f7dc6f9d8ad90d3545a37fb/select-product"
      - name: "DockerHub"
        logo: "../assets/icons/docker.png"
        subtitle: "DockerHub"
        url: "https://hub.docker.com/"
      - name: "Azure"
        logo: "../assets/icons/azure.webp"
        subtitle: "Microsoft Azure"
        url: "https://portal.azure.com/?quickstart=True#blade/Microsoft_Azure_Resources/QuickstartCenterBlade"

  - name: "Services /  Utilities"
    icon: "fas fa-tools"
    items:
      - name: "Plex"
        logo: "../assets/icons/plex.png"
        subtitle: "Movies, TV Shows"
        url: "http://192.168.100.203:32400/web/index.html#!/"
      - name: "AdGuard Home"
        logo: "../assets/icons/AdGuardHome.webp"
        subtitle: "DNS Ad blocker, local DNS"
        url: "http://192.168.100.10/"
      - name: "Mullvad VPN"
        logo: "../assets/icons/mullvad.png"
        subtitle: "VPN, Plex port-forwarding"
        url: "https://mullvad.net/en/account/#/login?next=%2F"
      - name: "LabGopher"
        logo: "../assets/icons/labgoupher.png"
        subtitle: "Deals on server hardware"
        url: "https://www.labgopher.com/"

  - name: "Servers"
    icon: "fas fa-industry"
    items:
      - name: "Proxmox"
        logo: "../assets/icons/proxmox.png"
        subtitle: "Proxmox Virtual Environment"
        url: "https://192.168.100.185:8006/"
      - name: "Portainer"
        logo: "../assets/icons/portainer.png"
        subtitle: "Docker images management"
        url: "http://192.168.100.208/#!/2/docker/dashboard"
      - name: "OMV local"
        logo: "../assets/icons/omv.png"
        subtitle: "OpenMediaVault"
        url: "https://192.168.100.202/#/dashboard"
      - name: "OMV public"
        logo: "../assets/icons/omv.png"
        subtitle: "OpenMediaVault"
        url: "https://192.168.100.205/#/dashboard"

  - name: "Hardware"
    icon: "fas fa-server"
    items:
      - name: "Router"
        logo: "../assets/icons/opnsense.png"
        subtitle: "OPNSense"
        url: "http://192.168.100.1/"
      - name: "Switch"
        logo: "../assets/icons/ubiquiti.png"
        subtitle: "Ubiquiti"
        url: "https://192.168.207.16/"
      - name: "Access Point"
        logo: "../assets/icons/linksys.webp"
        subtitle: "Linksys"
        url: "http://192.168.200.11/wireless/wireless_basic.shtml"
