version: "2"
services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - /home/benjamin/portainer/homer/assets:/www/assets
    environment:
      - UID=1000
      - GID=1000
    restart: unless-stopped
    networks:
      hostNetwork:
        ipv4_address: 192.168.100.53

networks:
  hostNetwork:
    external: true
